version: "3"
services:
  legado-rest-api:
    image: node:8.10.0
    working_dir: "/app"
    ports:
      - 3001:3001
    volumes:
      - "./legado-rest-api/:/app"
    command: bash -c "npm install && node app.js"
  frontend:
    image: node:8.10.0
    working_dir: "/app"
    ports:
      - 3000:3000
    volumes:
      - "./frontend/:/app"
    command: bash -c "npm install && npm start"
  backend:
    image: maven:3.6.0-jdk-8-alpine
    working_dir: "/app"
    links:
      - legado-rest-api:legado-rest-api
    ports:
      - 8080:8080
    volumes:
      - "./backend/:/app"
    command: bash -c "mvn spring-boot:run"